### ISSUE TITLE
类比推理

### ISSUE THREAD

**Issue by iggcloud** [LeadroyaL/fastjson-blacklist#4]
![image](https://user-images.githubusercontent.com/16320492/65487458-83156e00-ded9-11e9-9817-80e49b274980.png)
上面那个列表有`bsh`
但是下面那个列表没有
而且正好有一个未知的
![image](https://user-images.githubusercontent.com/16320492/65487547-b2c47600-ded9-11e9-9056-9f1660501419.png)

是不是可以推出这个未知的黑名单就是`bsh`呢 :-)

**Comment by LeadroyaL** [comment]
经过计算，很遗憾并不是，建议你亲自动手试试看。

**Comment by iggcloud** [comment]
好吧，:smile: ，打扰了~~

**Comment by Ramos-dev** [comment]
可能是阿里巴巴内部的类，或者是代码写错了？

**Comment by m4ra7h0n** [comment]
也有可能是故意混淆
